# Generated by Django 5.0.4 on 2024-04-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='women',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='women',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='women',
            name='time_update',
        ),
    ]
